name: proyecto_torneos
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1
  cached_network_image: ^3.4.1
  cached_network_svg_image: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  uuid: ^4.5.1
  syncfusion_flutter_datagrid: ^28.1.41
  skeletons: ^0.0.3
  image_picker: ^1.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
