name: proyecto_torneos
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  permission_handler: any
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
