// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyITrviB5zYQINIYV1E0JWTOVZfYCFrA',
    appId: '1:59431452908:web:e5da15ffb56a4ebb9965c9',
    messagingSenderId: '59431452908',
    projectId: 'torneos-pe',
    authDomain: 'torneos-pe.firebaseapp.com',
    storageBucket: 'torneos-pe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2kk7GBaWsno8tqwD5FX4zMU8k3pWD86w',
    appId: '1:59431452908:android:0ef941721dc22aae9965c9',
    messagingSenderId: '59431452908',
    projectId: 'torneos-pe',
    storageBucket: 'torneos-pe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1UpGIYESuTn6PlGe625xLChel0-P6wA',
    appId: '1:59431452908:ios:203b1c99597649789965c9',
    messagingSenderId: '59431452908',
    projectId: 'torneos-pe',
    storageBucket: 'torneos-pe.firebasestorage.app',
    iosBundleId: 'com.example.proyectoTorneos',
  );
}
